name: Demo CI

on:   
  push:
    branches:
      - main

  pull_request:

  # Run manually.
  workflow_dispatch:

jobs:
  build-image:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read

    outputs:
      version: ${{ steps.variables.outputs.version }}
      registry: ${{ steps.variables.outputs.registry }}
      env-name: ${{ steps.variables.outputs.env-name }}
      app-name: ${{ steps.variables.outputs.app-name }}

    steps:
      - uses: actions/checkout@v2

      - name: Set variables
        id: variables
        run: |
          version=${GITHUB_SHA}
          if [[ "${{ github.event_name }}" == "push" ]]; then
            version=$(<VERSION)
          fi
          env_name="staging"
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            env_name="pr"
          fi
          app_name="guestbook-${env_name}"
          echo "::set-output name=version::${version}"
          echo "::set-output name=registry::ghcr.io/${{ github.repository_owner }}"
          echo "::set-output name=env-name::${env_name}"
          echo "::set-output name=app-name::${app_name}"
      - name: Build image
        env:
          VERSION: ${{ steps.variables.outputs.version }}
          REGISTRY: ${{ steps.variables.outputs.registry }}
        run: |
          make build
      - name: Log in to registry
        run: |
          echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u ${{ github.actor }} --password-stdin
      - name: Push image
        env:
          VERSION: ${{ steps.variables.outputs.version }}
          REGISTRY: ${{ steps.variables.outputs.registry }}
        run: |
          make push
